---
- name: Configuring updates on all servers
  hosts: all
  become: true

  handlers:
    - name: Handler added
      import_tasks: handlers/nginx.yml

  pre_tasks: 
   - name: Load the variable files.
     include_vars: "{{ item }}"
     with_first_found:
      - "vars/apache_{{ ansible_os_family }}.yml"
      - "vars/apache_default.yml"

  tasks:
   - name: Sample tasks to be performed.
     import_tasks: tasks/sampletasks.yml
...
